35 login redes sociais
fga-eps-mds/2023.2-UnB-TV-Users pull request #3
Opened 2023-10-23 02:00 UTC by savioc2

2023-10-27 22:53 UTC, DaviMarinho approved these changes
LGTM!

2023-10-31 14:43 UTC, nYCSTs requested changes
Realizar correções solicitadas. Em relação aos testes, resolver os problemas de import como modulo e, se necessário, fazer ajustes nos testes que temos atualmente.

2023-10-31 14:43 UTC, nYCSTs commented on src/__pycache__/__init__.cpython-310.pyc
Remover todas pastas de pycache

2023-10-31 14:43 UTC, nYCSTs commented on src/main.py
> +app.include_router(router=facebookController.facebook)
Utilizar prefix /api tanto no googleController quanto no facebookController

2023-10-31 14:43 UTC, nYCSTs commented on src/application/__pycache__/__init__.cpython-39.pyc
Remover pasta application, já que não está sendo usada

2023-10-31 14:43 UTC, nYCSTs commented on src/domain/repositories/authSchema.py
Nós já temos os schemas em src/domain. Ajustar o que já tem e decidir onde vão ficar pra evitar duplicação.

2023-10-31 14:43 UTC, nYCSTs commented on src/interfaces/controllers/__init.py
Remover pasta pai já que não está sendo usada para nada. Se for usar, ajustar nome do arquivo init que está com nome errado

2023-10-31 14:43 UTC, nYCSTs commented on src/model/__init.py
Arquivo init com nome errado. Já temos um init criado para essa pasta

2023-10-31 14:43 UTC, nYCSTs commented on src/domain/repositories/__init.py
Se for manter essa pasta de repositories, ajustar nome do arquivo init.

2023-10-31 23:31 UTC, castroricardo1 commented on src/__pycache__/__init__.cpython-310.pyc
Removido

2023-11-01 01:48 UTC, nYCSTs requested changes

2023-11-01 01:48 UTC, nYCSTs commented on src/controller/googleController.py
> +from src.repository import userRepository
Ajustar import

2023-11-01 01:48 UTC, nYCSTs commented on src/main.py
> +from fastapi import FastAPI, Request, HTTPException, Depends
Import duplicado. Remover um dos dois

2023-11-01 12:32 UTC, nYCSTs approved these changes
LGTM

2023-11-01 14:14 UTC, merged